###Cadastrar usuário
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "name": "Juan Nascimento",
    "email": "juannascimento@condominios.com.br",
    "password": "KW4aXw37nG",
    "cpf": "49464963603",
    "cep": "88130680"
}

###Autenticar usuário
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "juannascimento@condominios.com.br",
    "password": "KW4aXw37nG"
}


###Encontrar um usuário por ID

GET http://localhost:3000/auth/1

###Encontrar um usuário por e-mail

GET http://localhost:3000/auth?email=dadafds@fasda.com

###Deletar usuário por ID

DELETE http://localhost:3000/auth/1

###Atualizar usuário por ID

PATCH http://localhost:3000/auth/1
content-type: application/json

{
    "email": "aaaaa@aaaaa.com"
}