###Cadastrar usuário
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "name": "Adakjd Aklsadjaldkj",
    "email": "dadafds@fasda.com",
    "password": "asdadg",
    "cpf": "12345678978",
    "cep": "1234567"
}

###Encontrar um usuário por ID

GET http://localhost:3000/auth/1

###Encontrar um usuário por e-mail

GET http://localhost:3000/auth?email=dadafds@fasda.com

###Deletar usuário por ID

DELETE http://localhost:3000/auth/1

###Atualizar usuário por ID

PATCH http://localhost:3000/auth/1
content-type: application/json

{
    "email": "aaaaa@aaaaa.com"
}